# What is NumPy?
1. NumPy (Numerical Python) is an open-source Python library that's used in almost every field of science and engineering.
2. It's the backbone of other Python scientific packages like SciPy, Matplotlib, pandas, etc.
3. The power of NumPy comes from its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python.


**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing



In [ ]:
# Installing Numpy
!pip install numpy

# Importing NumPy

In [ ]:
import numpy

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
# Give alias name ( Recommended but not Mandatory )
import numpy as np

# Creating Arrays

In [ ]:
# Create a 1D array
arr_1d = np.array([1, 2, 3])
print("1D Array:", arr_1d)

1D Array: [1 2 3]


In [ ]:
list1 = [1, 2, 3]
list1

[1, 2, 3]

In [ ]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# For Loop to square numbers.
L = range(1000)
# print(L)
%timeit [i**2 for i in L]

229 µs ± 2.59 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# For Loop to square numbers using Numpy
a = np.arange(1000)
%timeit a**2

947 ns ± 156 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# 2D Array
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [3,5,7]])
print("2D Array:", arr_2d)

2D Array: [[1 2 3]
 [4 5 6]
 [3 5 7]]


In [ ]:
# Attributes of arrays
print("Shape:", arr_2d.shape)

Shape: (2, 3)


In [ ]:
print("Size:", arr_2d.size)

Size: 6


In [ ]:
print("Data type:", arr_2d.dtype)

Data type: int64


In [ ]:
print("Number of dimensions:", arr_2d.ndim)

Number of dimensions: 2


In [ ]:
len(arr_2d)

3

In [ ]:
# Create a 1D array
arr_1d = np.array([1, 2, 3])
len(arr_1d)

3

In [ ]:
c = np.array([[[0, 1, 3], [2, 3, 5]], [[4, 5, 6], [6, 7, 8]]])

c

array([[[0, 1, 3],
        [2, 3, 5]],

       [[4, 5, 6],
        [6, 7, 8]]])

In [ ]:
c.ndim

3

In [ ]:
c.shape

(2, 2, 3)

In [ ]:
len(c)

2

In [ ]:
c.size

12

# Functions for Creating Arrays

In [ ]:
a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1,20,5) # Start, end ( exclusve ), Step
b

array([ 1,  6, 11, 16])

In [ ]:
c = np.linspace(0,1,6) # Start, End, Number of Points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
c = np.linspace(0,10,5) # Start, End, Number of Points
c

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
ones_array = np.ones((3,9))
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.eye(3) # Returns a 2D array with ones on diagonal and zeros elsewhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
d = np.eye(3, 2) # 3 is number of rows, 2 is number of columns, index of diagonal start with 0
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
#create array using diag function
diagonal = np.diag([1, 2, 3, ]) #construct a diagonal array.
diagonal

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.diag(diagonal) # Extract diagonal

array([1, 2, 3])

In [ ]:
# Create an array with a specific value
full = np.full((2, 3), 7)
print("Full of 7s:\n", full)

Full of 7s:
 [[7 7 7]
 [7 7 7]]


In [ ]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
random_array = np.random.rand(4)
random_array

array([0.62623089, 0.74743315, 0.86999152, 0.60279205])

# Data Types

In [ ]:
a = np.arange(10)

a.dtype

dtype('int64')

In [ ]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))
b = np.ones((3,3))

print(a)
print(" *************** ")
print(b)

print(" *************** ")
print("Data Type of a is : ", a.dtype)
print("Data Type of b is : ", b.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 *************** 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 *************** 
Data Type of a is :  float64
Data Type of b is :  float64


In [ ]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


In [ ]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

In [ ]:
# Creating an array with mixed types
obj_array = np.array([1, "a", True, np.array([1, 2, 3])], dtype = 'O')
print("Object array:", obj_array)
print(obj_array.dtype)

Object array: [1 'a' True array([1, 2, 3])]
object


obj_array is a NumPy array with a data type of 'O', meaning it can hold different types of Python objects. Each element can be accessed just like in any other NumPy array, but operations on the array will be limited by the fact that it contains mixed types, and many of NumPy's optimizations for numerical computations won't apply.

# Indexing and Slicing


In [ ]:
a = np.arange(0,10, 2)
print(a)
print(a[3])  #indices begin at 0, like other Python sequences (and C/C++)

[0 2 4 6 8]
6


In [ ]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a)

print("******************")

print(a[1, 4])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
******************


IndexError: index 4 is out of bounds for axis 1 with size 3

In [ ]:
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
#assigning value
a[2, 1] = 50

a

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0, 50,  3]])

In [ ]:
a = np.arange(20)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a[1:10:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7, 9])

In [ ]:
#we can also combine assignment and slicing:

a = np.arange(10)
print(a)
a[5:] = 10

print("******* After ********")
print(a)

[0 1 2 3 4 5 6 7 8 9]
******* After ********
[ 0  1  2  3  4 10 10 10 10 10]


In [ ]:
b = np.arange(5)
b[::-1]

array([4, 3, 2, 1, 0])

In [ ]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [ ]:

# Create a 3D array
# Shape is (2, 3, 4) -> 2 blocks, 3 rows, 4 columns
array_3d = np.array([[[ 0,  1,  2,  3],
                      [ 4,  5,  6,  7],
                      [ 8,  9, 10, 11]],

                     [[12, 13, 14, 15],
                      [16, 17, 18, 19],
                      [20, 21, 22, 23]]])

print("Original 3D Array:\n", array_3d)

Original 3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# Let's access the element 18, which is in the second block (index 1),
# second row (index 1) of that block, and third column (index 2) in that row.
element = array_3d[1, 1, 2]
print("Accessed Element:", element)

Accessed Element: 18


In [ ]:
# Slicing a sub-array
# Let's extract a 2D array from the first block
sub_array_2d = array_3d[0, :, :]
print("Extracted 2D Array from first block:\n", sub_array_2d)

Extracted 2D Array from first block:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Slicing to get specific rows across all blocks
# Here, we get the second row (index 1) from both blocks
rows_across_blocks = array_3d[:, 1, :]
print("Second row across all blocks:\n", rows_across_blocks)

Second row across all blocks:
 [[ 4  5  6  7]
 [16 17 18 19]]


In [ ]:
# Slicing to get a column across all blocks and rows
# Let's get the third column (index 2) across all blocks and rows
column_across_blocks = array_3d[:, :, 2]
print("Third column across all blocks and rows:\n", column_across_blocks)


Third column across all blocks and rows:
 [[ 2  6 10]
 [14 18 22]]


# Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block.

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, b)

True

In [ ]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [ ]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)

c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, c)

False

In [ ]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])